#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Translation pipeline for the Klinik Psixiatriya book.

Guarantees IDENTICAL page structure: HTML is tokenised, only text segments are
swapped; markup bytes are never regenerated by a model.

Subcommands:
  extract            AZ HTML -> _translate/az/<file>.json (ordered segments)
  chunk              az segments -> _translate/chunks/<id>.json (translator work units)
  inject <lang>      merge _translate/<lang>/out/<id>.json -> klinik-psixiatriya/<lang>/
  status <lang>      show which chunks are done / missing / invalid
"""
import json, re, shutil, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
BOOK = ROOT / 'klinik-psixiatriya'
CHUNK_BUDGET = 7000  # chars of source text per translator chunk

SKIP_FILES = {'admin-corrections.html'}
ASSETS = ['style.css', 'duzelis.css', 'duzelis.js']

TOKEN_RE = re.compile(r'(?s)(<script\b[^>]*>.*?</script>|<style\b[^>]*>.*?</style>|<!--.*?-->|<[^>]+>)')
LETTER_RE = re.compile(r'[A-Za-zƏəĞğİıÖöŞşÜüÇçЀ-ӿ]')
# translatable attributes on any tag
ATTR_RE = re.compile(r'\b(title|alt|placeholder|aria-label|data-tip)\s*=\s*"([^"]+)"')
META_RE = re.compile(r'<meta\s[^>]*?(?:name|property)\s*=\s*"(description|keywords|og:title|og:description)"[^>]*?>', re.I)
CONTENT_RE = re.compile(r'\bcontent\s*=\s*"([^"]*)"')
JSONLD_KEYS = ('name', 'about', 'description', 'keywords')

LANG_META = {
    'en': {'lang': 'en', 'locale': 'en_US', 'inlang': 'en'},
    'ru': {'lang': 'ru', 'locale': 'ru_RU', 'inlang': 'ru'},
    'tr': {'lang': 'tr', 'locale': 'tr_TR', 'inlang': 'tr'},
}


def book_files():
    return sorted(p for p in BOOK.glob('*.html') if p.name not in SKIP_FILES)


def walk_segments(html):
    """Yield ordered segments: ('text', tok_idx, pre, core, post) |
    ('attr', tok_idx, attrname, occurrence, value) |
    ('meta', tok_idx, key, value) | ('jsonld', tok_idx, key, value).
    Token list returned too."""
    toks = TOKEN_RE.split(html)
    segs = []
    for idx, tok in enumerate(toks):
        if idx % 2 == 0:  # text between tags
            if not tok or not LETTER_RE.search(tok):
                continue
            pre = tok[:len(tok) - len(tok.lstrip())]
            post = tok[len(tok.rstrip()):]
            core = tok[len(pre):len(tok) - len(post)] if post else tok[len(pre):]
            if core and LETTER_RE.search(core):
                segs.append(('text', idx, pre, core, post))
        else:
            low = tok[:60].lower()
            if low.startswith('<script'):
                if 'application/ld+json' in low:
                    body = re.search(r'(?s)>(.*)</script>', tok).group(1)
                    try:
                        data = json.loads(body)
                    except Exception:
                        continue
                    for k in JSONLD_KEYS:
                        v = data.get(k)
                        if isinstance(v, str) and LETTER_RE.search(v):
                            segs.append(('jsonld', idx, k, v))
                continue
            if low.startswith('<style') or low.startswith('<!--'):
                continue
            m = META_RE.match(tok)
            if m:
                cm = CONTENT_RE.search(tok)
                if cm and LETTER_RE.search(cm.group(1)):
                    segs.append(('meta', idx, m.group(1).lower(), cm.group(1)))
                continue
            for occ, am in enumerate(ATTR_RE.finditer(tok)):
                if LETTER_RE.search(am.group(2)):
                    segs.append(('attr', idx, am.group(1), occ, am.group(2)))
    return toks, segs


def seg_value(s):
    return s[3] if s[0] == 'text' else (s[4] if s[0] == 'attr' else s[3])


def cmd_extract():
    outdir = HERE / 'az'
    outdir.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for p in book_files():
        html = p.read_text(encoding='utf-8')
        _, segs = walk_segments(html)
        items = [{'i': i, 't': seg_value(s)} for i, s in enumerate(segs)]
        (outdir / (p.name + '.json')).write_text(
            json.dumps({'file': p.name, 'segments': items}, ensure_ascii=False, indent=0),
            encoding='utf-8')
        manifest[p.name] = {'segments': len(items),
                            'chars': sum(len(x['t']) for x in items)}
    (HERE / 'manifest.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=1), encoding='utf-8')
    tot = sum(v['chars'] for v in manifest.values())
    print(f"extracted {len(manifest)} files, {sum(v['segments'] for v in manifest.values())} segments, {tot:,} chars")


def cmd_chunk():
    chdir = HERE / 'chunks'
    chdir.mkdir(exist_ok=True)
    manifest = json.loads((HERE / 'manifest.json').read_text(encoding='utf-8'))
    chunks = []
    for fname in sorted(manifest):
        data = json.loads((HERE / 'az' / (fname + '.json')).read_text(encoding='utf-8'))
        items = data['segments']
        lo = 0
        part = 0
        while lo < len(items):
            hi = lo
            chars = 0
            while hi < len(items) and (chars < CHUNK_BUDGET or hi == lo):
                chars += len(items[hi]['t'])
                hi += 1
            cid = f"{fname[:-5]}__{part:02d}"
            (chdir / (cid + '.json')).write_text(
                json.dumps({'id': cid, 'file': fname,
                            'segments': items[lo:hi]}, ensure_ascii=False, indent=0),
                encoding='utf-8')
            chunks.append({'id': cid, 'file': fname, 'lo': lo, 'hi': hi, 'chars': chars})
            lo = hi
            part += 1
    (HERE / 'chunks_index.json').write_text(json.dumps(chunks, ensure_ascii=False, indent=1), encoding='utf-8')
    print(f"{len(chunks)} chunks written (budget {CHUNK_BUDGET} chars)")


def load_translations(lang, fname):
    """Merge all out chunks of a file -> {i: text}. Returns (map, problems)."""
    outdir = HERE / lang / 'out'
    merged, problems = {}, []
    for p in sorted(outdir.glob(f"{fname[:-5]}__*.json")):
        try:
            arr = json.loads(p.read_text(encoding='utf-8'))
        except Exception as e:
            problems.append(f"{p.name}: bad json ({e})")
            continue
        if isinstance(arr, dict):
            arr = arr.get('segments', [])
        for it in arr:
            if not isinstance(it, dict) or 'i' not in it or 't' not in it or not isinstance(it['t'], str):
                problems.append(f"{p.name}: bad item {str(it)[:60]}")
                continue
            merged[it['i']] = it['t']
    return merged, problems


def esc_attr(s):
    return s.replace('"', '&quot;')


def localize_meta(html, lang, fname):
    meta = LANG_META[lang]
    html = re.sub(r'(<html\b[^>]*\blang=")az(")', r'\g<1>' + meta['lang'] + r'\2', html, count=1)
    html = html.replace('content="az_AZ"', f'content="{meta["locale"]}"')
    html = re.sub(r'"inLanguage":"az"', f'"inLanguage":"{meta["inlang"]}"', html)
    # canonical + og:url + absolute self-links -> language subtree; canonical points to the page itself
    html = re.sub(r'(<link rel="canonical" href=")https://ragimoff\.org/klinik-psixiatriya/[^"]*(")',
                  r'\g<1>' + f'https://ragimoff.org/klinik-psixiatriya/{lang}/{fname}' + r'\2', html)
    html = html.replace('https://ragimoff.org/klinik-psixiatriya/',
                        f'https://ragimoff.org/klinik-psixiatriya/{lang}/')
    return html


def cmd_inject(lang, only=None):
    assert lang in LANG_META
    dest = BOOK / lang
    dest.mkdir(exist_ok=True)
    manifest = json.loads((HERE / 'manifest.json').read_text(encoding='utf-8'))
    done = failed = 0
    for fname in sorted(manifest):
        if only and fname not in only:
            continue
        n_expected = manifest[fname]['segments']
        tr, problems = load_translations(lang, fname)
        missing = [i for i in range(n_expected) if i not in tr]
        if problems or missing:
            failed += 1
            msg = f"[skip] {fname}: "
            if missing:
                msg += f"missing {len(missing)}/{n_expected} segments (e.g. {missing[:5]}) "
            if problems:
                msg += '; '.join(problems[:3])
            print(msg)
            continue
        html = (BOOK / fname).read_text(encoding='utf-8')
        toks, segs = walk_segments(html)
        assert len(segs) == n_expected, f"{fname}: source changed since extract ({len(segs)} vs {n_expected})"
        # group segments by token
        by_tok = {}
        for i, s in enumerate(segs):
            by_tok.setdefault(s[1], []).append((i, s))
        for tidx, group in by_tok.items():
            tok = toks[tidx]
            kind = group[0][1][0]
            if kind == 'text':
                i, s = group[0]
                toks[tidx] = s[2] + tr[i] + s[4]
            elif kind == 'meta':
                i, s = group[0]
                toks[tidx] = tok.replace(f'content="{s[3]}"', f'content="{esc_attr(tr[i])}"', 1)
            elif kind == 'jsonld':
                body = re.search(r'(?s)(>)(.*)(</script>)', tok)
                data = json.loads(body.group(2))
                for i, s in group:
                    data[s[2]] = tr[i]
                toks[tidx] = tok[:tok.index('>') + 1] + '\n' + json.dumps(data, ensure_ascii=False) + '\n</script>'
            elif kind == 'attr':
                def sub(m, _g=group):
                    for i, s in _g:
                        if s[0] == 'attr' and m.group(1) == s[2] and m.group(2) == s[4]:
                            return f'{m.group(1)}="{esc_attr(tr[i])}"'
                    return m.group(0)
                toks[tidx] = ATTR_RE.sub(sub, tok)
        out = ''.join(toks)
        out = localize_meta(out, lang, fname)
        (dest / fname).write_text(out, encoding='utf-8')
        done += 1
    for a in ASSETS:
        src = BOOK / a
        if src.exists():
            shutil.copy2(src, dest / a)
    print(f"inject[{lang}]: {done} written, {failed} incomplete -> {dest}")


def cmd_status(lang):
    chunks = json.loads((HERE / 'chunks_index.json').read_text(encoding='utf-8'))
    outdir = HERE / lang / 'out'
    outdir.mkdir(parents=True, exist_ok=True)
    ok = bad = todo = 0
    bad_ids, todo_ids = [], []
    for c in chunks:
        p = outdir / (c['id'] + '.json')
        if not p.exists():
            todo += 1; todo_ids.append(c['id']); continue
        try:
            arr = json.loads(p.read_text(encoding='utf-8'))
            if isinstance(arr, dict):
                arr = arr.get('segments', [])
            ids = {it['i'] for it in arr if isinstance(it, dict) and isinstance(it.get('t'), str) and it['t'].strip()}
            expect = set(range(c['lo'], c['hi']))
            if expect <= ids:
                ok += 1
            else:
                bad += 1; bad_ids.append(c['id'])
        except Exception:
            bad += 1; bad_ids.append(c['id'])
    print(f"status[{lang}]: {ok} ok, {bad} invalid, {todo} todo of {len(chunks)}")
    if bad_ids:
        print(' invalid:', ' '.join(bad_ids[:20]))
    if todo_ids:
        print(' todo:', ' '.join(todo_ids[:20]), '...' if len(todo_ids) > 20 else '')
    return todo_ids + bad_ids


if __name__ == '__main__':
    cmd = sys.argv[1] if len(sys.argv) > 1 else ''
    if cmd == 'extract':
        cmd_extract()
    elif cmd == 'chunk':
        cmd_chunk()
    elif cmd == 'inject':
        cmd_inject(sys.argv[2], set(sys.argv[3:]) or None)
    elif cmd == 'status':
        cmd_status(sys.argv[2])
    else:
        print(__doc__)
